@startuml
'Start PlantUML
'Use Cases using in DevOps help to solve the problems and improve performance of the system.

actor user as "Organization User"

'Defined the system using rectangles

rectangle Database

rectangle "World factbook Information System " {
   usecase UC1 as "get all population data of human being according to the usecase to the 1 to 16"


    usecase UCa as "Print all information"

'To provide a name for usecases (use case UC1 as use case 1)

    user - UC1
    UC1 ..> UCa : include
    UC1 - Database

}
'End PlantUML
@enduml
